DSA:
  [
    QuickSort,
    Queue,
    Stack,
    SinglyLinkedList,
    DoublyLinkedList,
    ArrayList,
    BubbleSort,
    LinearSearchList,
    MergeSort,
    RingBuffer,
    MinHeap,
    TwoCrystalBalls,
    BinarySearchList,
    MazeSolver,
    Trie,
    DFSOnBST,
  ]
